const catalog = {
  shampoingEquilibre: { title: "Shampoing Équilibre", desc: "Nettoie les racines sans les dessécher et aide à garder une sensation fraîche.", price: "14,90€", format: "Shampoing solide", ingredients: "Tous types de cheveux", usage: "2 à 3 fois par semaine", image: "assets/images/concept-products/shampoing-solide-cuir-chevelu.png" },
  shampoingPurete: { title: "Shampoing Pureté", desc: "Nettoie les racines qui regraissent vite et laisse le cuir chevelu léger.", price: "14,90€", format: "250 ml", ingredients: "Argile verte + zinc", usage: "2 fois par semaine", image: "assets/images/concept-products/shampoing-purete.png" },
  shampoingApaisement: { title: "Shampoing Apaisement", desc: "Nettoie en douceur les cuirs chevelus sujets aux tiraillements et inconforts.", price: "14,90€", format: "250 ml", ingredients: "Avoine + panthénol", usage: "À chaque lavage", image: "assets/images/concept-products/shampoing-apaisement.png" },
  shampoingReparation: { title: "Shampoing Réparation", desc: "Nettoie les cheveux abîmés et prépare les longueurs au soin réparateur.", price: "15,90€", format: "250 ml", ingredients: "Protéines végétales + huile de coco", usage: "2 à 3 fois par semaine", image: "assets/images/concept-products/shampoing-reparation.png" },
  apresHydratant: { title: "Après-shampoing Hydratant léger", desc: "Démêle sans alourdir et apporte douceur aux longueurs et pointes.", price: "15,90€", format: "200 ml", ingredients: "Acide hyaluronique + aloe vera", usage: "Après chaque shampoing", image: "assets/images/concept-products/apres-shampoing-hydratant-leger.png" },
  apresNourrissant: { title: "Après-shampoing Nourrissant-réparateur", desc: "Nourrit les longueurs sèches et aide à retrouver une fibre plus souple.", price: "16,90€", format: "200 ml", ingredients: "Beurre de karité + protéines végétales", usage: "Après chaque shampoing", image: "assets/images/concept-products/apres-shampoing-nourrissant-reparateur.png" },
  serumScalp: { title: "Sérum cuir chevelu apaisant", desc: "Soin ciblé sans rinçage pour calmer la sensation d'inconfort et hydrater les racines.", price: "22,90€", format: "30 ml", ingredients: "Niacinamide + panthénol", usage: "Quelques gouttes le soir, 3 fois par semaine", image: "assets/images/concept-products/serum-cuir-chevelu-apaisant.png" },
  exfoliantScalp: { title: "Exfoliant-purifiant cuir chevelu", desc: "Décolle les impuretés et résidus pour un cuir chevelu plus net.", price: "19,90€", format: "75 ml", ingredients: "Acide salicylique + argile verte", usage: "Une fois par semaine avant shampoing", image: "assets/images/concept-products/exfoliant-purifiant-cuir-chevelu.png" },
  masqueRepair: { title: "Masque réparation intense", desc: "Enveloppe les longueurs abîmées et redonne toucher doux et souplesse.", price: "21,90€", format: "200 ml", ingredients: "Céramides + huile d'argan", usage: "Une fois par semaine, 5 à 10 minutes", image: "assets/images/concept-products/masque-reparation-intense.png" },
  forceVitalite: { title: "Force & Vitalité", desc: "Cure quotidienne pensée pour accompagner la routine cheveux, peau et ongles.", price: "39,90€", format: "90 gélules", ingredients: "Collagène marin + zinc + vitamines B", usage: "1 gélule par jour pendant 3 mois", image: "assets/images/concept-products/force-vitalite-3-mois.png" }
};
const requestedKey = new URLSearchParams(window.location.search).get("product");
const key = catalog[requestedKey] ? requestedKey : "shampoingEquilibre";
const product = catalog[key];
const detail = document.querySelector("#product-detail");
const lifestyleImages = {
  hydration: "assets/images/product-lifestyle/hydratation.png",
  scalp: "assets/images/product-lifestyle/cuir-chevelu.png",
  repair: "assets/images/product-lifestyle/reparation.png",
  vitality: "assets/images/product-lifestyle/force-vitalite.png"
};
const lifestyleKey = key === "forceVitalite" ? "vitality" : key.includes("Purete") || key.includes("Apaisement") || key.includes("Scalp") ? "scalp" : key.includes("Reparation") || key.includes("Repair") || key.includes("Nourrissant") ? "repair" : "hydration";
const benefits = key.includes("Purete") || key.includes("exfoliant") ? ["Purifie", "Décolle les résidus", "Racines plus légères"] : key.includes("Apaisement") || key.includes("serum") ? ["Apaise", "Hydrate", "Cuir chevelu confortable"] : key.includes("Reparation") || key.includes("Repair") || key.includes("Nourrissant") ? ["Répare", "Nourrit", "Redonne de la souplesse"] : ["Nettoie en douceur", "Hydrate", "Routine quotidienne"];
detail.innerHTML = `<a class="back-link" href="index.html#produits">← Retour à la gamme</a><section class="product-detail-grid"><div class="product-gallery"><div class="product-detail-image"><img src="${product.image}" alt="${product.title}"></div><div class="product-thumbnails"><button class="is-selected" type="button"><img src="${product.image}" alt="Vue principale ${product.title}"></button><button type="button"><img src="${lifestyleImages[lifestyleKey]}" alt="Univers ${product.title}"></button></div></div><div class="product-detail-copy"><p class="eyebrow">Nouvelle gamme capillaire · Pré-lancement</p><p class="product-status">Concept en développement</p><h1>${product.title}</h1><p class="product-detail-desc">${product.desc}</p><div class="product-benefits">${benefits.map((benefit) => `<span>${benefit}</span>`).join("")}</div><p class="product-detail-price">${product.price}</p><button class="button button-dark" id="add-product">Ajouter au panier</button><div class="shipping-points"><span><strong>Livraison offerte</strong> dès 45€</span><span><strong>Paiement</strong> non connecté pour le moment</span></div><dl><div><dt>Format</dt><dd>${product.format}</dd></div><div><dt>Actifs</dt><dd>${product.ingredients}</dd></div><div><dt>Utilisation</dt><dd>${product.usage}</dd></div></dl><p class="product-detail-note">Produit en pré-lancement. Données de formulation à valider avant commercialisation.</p></div></section><section class="product-content-grid"><article><p class="eyebrow">Pour qui ?</p><h2>Un geste ciblé pour votre routine.</h2><p>${product.desc} Cette fiche présente un concept de gamme, à confirmer par formulation et tests avant mise en vente.</p></article><article class="product-content-image"><img src="${lifestyleImages[lifestyleKey]}" alt="Univers visuel ${product.title}"></article><article><p class="eyebrow">Conseils d'application</p><h2>Le bon geste, au bon moment.</h2><p>${product.usage}. Rincer si le produit est rincé. Éviter le contact avec les yeux.</p></article></section><section class="faq-section"><details open><summary>Quels sont les actifs clés ?</summary><p>${product.ingredients}.</p></details><details><summary>Quelle fréquence d'utilisation ?</summary><p>${product.usage}.</p></details><details><summary>Le produit est-il disponible ?</summary><p>Cette gamme est en pré-lancement. Les formules et informations finales restent à valider.</p></details></section>`;
function cart() { try { return JSON.parse(localStorage.getItem("respireCart") || "[]"); } catch { return []; } }
function updateCount() { document.querySelector("#product-cart-count").textContent = cart().reduce((sum, item) => sum + item.quantity, 0); }
document.querySelector("#add-product").addEventListener("click", () => { const items = cart(); const existing = items.find((item) => item.productKey === key); if (existing) existing.quantity += 1; else items.push({ productKey: key, quantity: 1 }); localStorage.setItem("respireCart", JSON.stringify(items)); updateCount(); document.querySelector("#add-product").textContent = "Ajouté au panier"; });
document.querySelectorAll(".product-thumbnails button").forEach((button) => button.addEventListener("click", () => { const image = button.querySelector("img"); const main = document.querySelector(".product-detail-image img"); main.src = image.src; main.alt = image.alt; document.querySelectorAll(".product-thumbnails button").forEach((item) => item.classList.toggle("is-selected", item === button)); }));
updateCount();
